# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_envio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Precio de Envío",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Tienda",
                "verbose_name_plural": "Configuraciones de Tienda",
            },
        ),
    ]
