# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="imagen_fondo_productos",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="config/",
                verbose_name="Fondo Página Productos",
            ),
        ),
    ]
