# Generated by Django 6.0.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_configuraciontienda_imagen_fondo_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuraciontienda",
            name="slider_link",
            field=models.URLField(blank=True, verbose_name="Link del Slider (Saber Más)", help_text="URL del botón 'Saber Más' en el slider de inicio"),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="texto_slider_superior",
            field=models.CharField(blank=True, max_length=200, verbose_name="Texto superior del slider", help_text="Texto pequeño arriba del título (ej: 'Esto es Kurovoid')"),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="texto_slider_inferior",
            field=models.CharField(blank=True, max_length=200, verbose_name="Texto inferior del slider", help_text="Texto debajo del título (ej: 'Tu destino de moda online')"),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="texto_exclusivos_subtitulo",
            field=models.CharField(blank=True, max_length=300, verbose_name="Subtítulo Productos Exclusivos", help_text="Texto bajo el título 'Productos Exclusivos' en la página de inicio"),
        ),
        migrations.AddField(
            model_name="configuraciontienda",
            name="texto_productos_subtitulo",
            field=models.CharField(blank=True, max_length=300, verbose_name="Subtítulo Página Productos", help_text="Texto bajo el título en la página de productos"),
        ),
    ]
