# Generated by Django 6.0.5 on 2026-05-31 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_envio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_cliente',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
