from django.urls import path

from . import views

app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardHomeView.as_view(), name="home"),
    path("productos/", views.ProductListAdminView.as_view(), name="product_list"),
    path("productos/nuevo/", views.ProductCreateView.as_view(), name="product_create"),
    path("productos/editar/<int:pk>/", views.ProductUpdateView.as_view(), name="product_update"),
    path("productos/eliminar/<int:pk>/", views.ProductDeleteView.as_view(), name="product_delete"),
    path("ventas/", views.VentasView.as_view(), name="ventas"),
    path("pedidos/", views.OrderListView.as_view(), name="pedido_list"),
    path("pedidos/<int:pk>/", views.OrderDetailView.as_view(), name="pedido_detail"),
    path("usuarios/", views.UserListView.as_view(), name="usuario_list"),
    path("usuarios/<int:pk>/", views.UserDetailView.as_view(), name="usuario_detail"),
    path("categorias/", views.CategoryListView.as_view(), name="categoria_list"),
    path("categorias/nueva/", views.CategoryCreateView.as_view(), name="categoria_create"),
    path("categorias/editar/<int:pk>/", views.CategoryUpdateView.as_view(), name="categoria_update"),
    path("categorias/eliminar/<int:pk>/", views.CategoryDeleteView.as_view(), name="categoria_delete"),
    path("categorias/reordenar/", views.categoria_reordenar, name="categoria_reordenar"),
    path("categorias/toggle/<int:pk>/", views.categoria_toggle_active, name="categoria_toggle"),
    path("alertas/", views.AlertasView.as_view(), name="alertas"),
    path("alertas/reponer/<int:pk>/", views.producto_reponer_stock, name="reponer_stock"),
    path("productos/<int:pk>/imagen/subir/", views.producto_subir_imagen, name="producto_subir_imagen"),
    path("productos/imagen/<int:img_id>/eliminar/", views.producto_eliminar_imagen, name="producto_eliminar_imagen"),
    path("productos/<int:pk>/imagen/reordenar/", views.producto_reordenar_imagenes, name="producto_reordenar_imagenes"),
    path("productos/imagen/<int:img_id>/principal/", views.producto_imagen_principal, name="producto_imagen_principal"),
    path("productos/imagen/<int:img_id>/alt-text/", views.producto_actualizar_alt_text, name="producto_alt_text"),
    path("exportar/productos/", views.ExportProductosCSV, name="export_productos"),
    path("exportar/pedidos/", views.ExportPedidosCSV, name="export_pedidos"),
    path("personalizacion/", views.PersonalizacionView.as_view(), name="personalizacion"),
    path("personalizacion/slider/nueva/", views.CarouselCreateView.as_view(), name="carousel_create"),
    path("personalizacion/slider/editar/<int:pk>/", views.CarouselUpdateView.as_view(), name="carousel_update"),
    path("personalizacion/slider/eliminar/<int:pk>/", views.CarouselDeleteView.as_view(), name="carousel_delete"),
    path("colores/", views.ColorListView.as_view(), name="color_list"),
    path("colores/nuevo/", views.ColorCreateView.as_view(), name="color_create"),
    path("colores/editar/<int:pk>/", views.ColorUpdateView.as_view(), name="color_update"),
    path("colores/eliminar/<int:pk>/", views.ColorDeleteView.as_view(), name="color_delete"),
    path("colores/api/crear/", views.color_api_create, name="color_api_create"),
    path("tallas/", views.SizeListView.as_view(), name="size_list"),
    path("tallas/nueva/", views.SizeCreateView.as_view(), name="size_create"),
    path("tallas/editar/<int:pk>/", views.SizeUpdateView.as_view(), name="size_update"),
    path("tallas/eliminar/<int:pk>/", views.SizeDeleteView.as_view(), name="size_delete"),
    path("tallas/api/crear/", views.size_api_create, name="size_api_create"),
]
